mass : 2000 # (kg)
yaw_inertia : 3500 # (kgm2)
cg2axle_front : 1.0 # (m)
cg2axle_rear : 1.8 # (m)
corn_compliance_front : 0.3 # (rad/g)
corn_compliance_rear : 0.15 # (rad/g)
hand_road_gearratio : 16 # hand / road
gravity : 9.81 # (m/s2)
speed : 27.7 # (m/s)
skin_length : 4.0 # (m)
skin_width : 1.8 # (m)
skin_height : 1.5 # (m)
longacc_limit : 8 # (m/s2)
refsteer_limit : 0.4 # (rad)
