function [x, y] = cursor_joystick(cursor,...
	cursor_x_max, cursor_x_min,...
	cursor_y_max, cursor_y_min)

  x = 0;
  y = 0;
  if (cursor(1)<cursor_x_max &&...
    cursor(1)>cursor_x_min &&...
    cursor(2)<cursor_y_max &&...
    cursor(2)>cursor_y_min)
    x = (cursor(1) - cursor_x_min) /...
      (cursor_x_max - cursor_x_min) *...
      (1 - -1) + ...
      -1;
    y = (cursor(2) - cursor_y_min) /...
      (cursor_y_max - cursor_y_min) *...
      (1- -1) + ...
      -1;
  end